//! Tests for marking RPC methods as `#[deprecated]`.
//!
//! The `deny` below is part of the test: the code generated by the macros (and the attributes
//! they leave in place) must keep compiling in downstream crates that deny deprecation warnings.
#![deny(deprecated)]

use std::collections::HashSet;

use async_trait::async_trait;
use nimiq_jsonrpc_core::{Request, RpcError};
use nimiq_jsonrpc_server::{AllowListDispatcher, Dispatcher, MethodDeprecation, ModularDispatcher};
use serde_json::json;

#[derive(Default)]
struct TestService;

#[nimiq_jsonrpc_derive::service(rename_all = "camelCase")]
#[allow(dead_code)]
impl TestService {
    async fn current_method(&self, value: u32) -> Result<u32, RpcError> {
        Ok(value + 1)
    }

    #[deprecated = "use current_method instead"]
    async fn old_method(&self, value: u32) -> Result<u32, RpcError> {
        Ok(value + 1)
    }

    #[deprecated]
    async fn other_old_method(&self) -> Result<(), RpcError> {
        Ok(())
    }
}

/// The interface implemented by [`TraitService`]. Deprecations are marked here as well, so that
/// Rust callers of the trait get the compile-time warning.
#[async_trait]
trait ExampleInterface {
    async fn renamed_method(&self, value: u32) -> Result<u32, RpcError>;

    #[deprecated(since = "0.2.0", note = "use renamedMethod instead")]
    async fn legacy_method(&self, value: u32) -> Result<u32, RpcError>;
}

#[derive(Default)]
struct TraitService;

// On the methods of a trait impl Rust rejects `#[deprecated]` (`useless_deprecated`), so here the
// service macro consumes the attribute instead of leaving it in place.
#[nimiq_jsonrpc_derive::service(rename_all = "camelCase")]
#[async_trait]
impl ExampleInterface for TraitService {
    async fn renamed_method(&self, value: u32) -> Result<u32, RpcError> {
        Ok(value + 1)
    }

    #[deprecated(since = "0.2.0", note = "use renamedMethod instead")]
    async fn legacy_method(&self, value: u32) -> Result<u32, RpcError> {
        Ok(value + 1)
    }
}

/// Compile-time check: the proxy macro keeps `#[deprecated]` on the trait definition (that is
/// what warns Rust callers), and the generated client impl must still compile under the
/// `#![deny(deprecated)]` above.
#[nimiq_jsonrpc_derive::proxy(name = "ExampleProxy", rename_all = "camelCase")]
#[async_trait]
#[allow(dead_code)]
trait ExampleClient {
    type Error;

    async fn renamed_method(&self, value: u32) -> Result<u32, Self::Error>;

    #[deprecated(since = "0.2.0", note = "use renamedMethod instead")]
    async fn legacy_method(&self, value: u32) -> Result<u32, Self::Error>;
}

/// A logger capturing all warnings, so that tests can assert the deprecation log lines.
mod log_capture {
    use std::sync::Mutex;

    use log::{Level, LevelFilter, Log, Metadata, Record};

    static LOGS: Mutex<Vec<String>> = Mutex::new(Vec::new());

    struct Capture;

    impl Log for Capture {
        fn enabled(&self, metadata: &Metadata) -> bool {
            metadata.level() <= Level::Warn
        }

        fn log(&self, record: &Record) {
            if record.level() == Level::Warn {
                LOGS.lock().unwrap().push(record.args().to_string());
            }
        }

        fn flush(&self) {}
    }

    static CAPTURE: Capture = Capture;

    /// Installs the capturing logger. Idempotent, so every test using the capture can call it.
    pub fn init() {
        let _ = log::set_logger(&CAPTURE);
        log::set_max_level(LevelFilter::Warn);
    }

    pub fn contains(line: &str) -> bool {
        LOGS.lock().unwrap().iter().any(|logged| logged == line)
    }
}

#[test]
fn it_reports_deprecated_methods() {
    let service = TestService;

    // All methods are listed (renamed to camelCase).
    let mut methods = service.method_names();
    methods.sort();
    assert_eq!(
        methods,
        vec!["currentMethod", "oldMethod", "otherOldMethod"]
    );

    // Only the `#[deprecated]` ones show up here, along with their metadata.
    let mut deprecated = service.deprecated_methods();
    deprecated.sort_by_key(|deprecation| deprecation.method);
    assert_eq!(
        deprecated,
        vec![
            MethodDeprecation {
                method: "oldMethod",
                note: Some("use current_method instead"),
                since: None,
            },
            MethodDeprecation {
                method: "otherOldMethod",
                note: None,
                since: None,
            },
        ]
    );
}

#[tokio::test]
async fn deprecated_methods_still_dispatch() {
    let mut service = TestService;

    let request = Request::new(
        "oldMethod".to_owned(),
        Some(json!({ "value": 41 })),
        Some(json!(1)),
    );

    let (response, _notifier) = service
        .dispatch(request, None, 0, None)
        .await
        .expect("expected a response");

    assert_eq!(response.result, Some(json!(42)));
    assert!(response.error.is_none());
}

#[test]
fn it_reports_deprecated_methods_for_trait_impls() {
    let service = TraitService;

    let mut methods = service.method_names();
    methods.sort();
    assert_eq!(methods, vec!["legacyMethod", "renamedMethod"]);

    assert_eq!(
        service.deprecated_methods(),
        vec![MethodDeprecation {
            method: "legacyMethod",
            note: Some("use renamedMethod instead"),
            since: Some("0.2.0"),
        }]
    );
}

#[tokio::test]
async fn deprecated_trait_impl_methods_still_dispatch() {
    let mut service = TraitService;

    let request = Request::new(
        "legacyMethod".to_owned(),
        Some(json!({ "value": 41 })),
        Some(json!(1)),
    );

    let (response, _notifier) = service
        .dispatch(request, None, 0, None)
        .await
        .expect("expected a response");

    assert_eq!(response.result, Some(json!(42)));
    assert!(response.error.is_none());
}

#[tokio::test]
async fn dispatching_a_deprecated_method_logs_a_warning() {
    log_capture::init();

    let mut service = TraitService;
    let request = Request::new(
        "legacyMethod".to_owned(),
        Some(json!({ "value": 1 })),
        Some(json!(1)),
    );
    service.dispatch(request, None, 0, None).await;

    assert!(log_capture::contains(
        "Call to deprecated JSON-RPC method 'legacyMethod' (since 0.2.0): use renamedMethod instead"
    ));
}

#[test]
fn it_formats_all_deprecation_log_variants() {
    log_capture::init();

    for (note, since, expected) in [
        (None, None, "Call to deprecated JSON-RPC method 'foo'"),
        (
            Some("use bar"),
            None,
            "Call to deprecated JSON-RPC method 'foo': use bar",
        ),
        (
            None,
            Some("1.0"),
            "Call to deprecated JSON-RPC method 'foo' (since 1.0)",
        ),
        (
            Some("use bar"),
            Some("1.0"),
            "Call to deprecated JSON-RPC method 'foo' (since 1.0): use bar",
        ),
    ] {
        nimiq_jsonrpc_server::log_deprecated(&MethodDeprecation {
            method: "foo",
            note,
            since,
        });
        assert!(
            log_capture::contains(expected),
            "missing log line: {}",
            expected
        );
    }
}

#[test]
fn modular_dispatcher_aggregates_deprecated_methods() {
    let mut modular = ModularDispatcher::default();
    modular.add(TestService);
    modular.add(TraitService);

    let mut deprecated: Vec<&str> = modular
        .deprecated_methods()
        .iter()
        .map(|deprecation| deprecation.method)
        .collect();
    deprecated.sort();
    assert_eq!(
        deprecated,
        vec!["legacyMethod", "oldMethod", "otherOldMethod"]
    );
}

#[test]
fn allowlist_dispatcher_filters_deprecated_methods() {
    let allowlist: HashSet<String> = ["currentMethod".to_owned(), "oldMethod".to_owned()]
        .into_iter()
        .collect();
    let dispatcher = AllowListDispatcher::new(TestService, Some(allowlist));

    let mut methods = dispatcher.method_names();
    methods.sort();
    assert_eq!(methods, vec!["currentMethod", "oldMethod"]);

    let deprecated: Vec<&str> = dispatcher
        .deprecated_methods()
        .iter()
        .map(|deprecation| deprecation.method)
        .collect();
    assert_eq!(deprecated, vec!["oldMethod"]);
}
